# Generated by Django 4.0.10 on 2023-10-17 16:27

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your Title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='add additional text here', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
