# Generated by Django 4.0.10 on 2023-10-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='email address', max_length=100)),
                ('full_name', models.CharField(help_text='First and Last name', max_length=100)),
            ],
        ),
    ]
